services:
  foundry:
    image: felddy/foundryvtt:release
    container_name: foundryvtt
    restart: unless-stopped
    volumes:
      - foundry_data:/data
    environment:
      - FOUNDRY_USERNAME=${FOUNDRY_USERNAME}
      - FOUNDRY_PASSWORD=${FOUNDRY_PASSWORD}
      - FOUNDRY_ADMIN_KEY=${FOUNDRY_PASSWORD}
      - FOUNDRY_LICENSE_KEY=${FOUNDRY_LICENSE_KEY}
      - FOUNDRY_HOSTNAME=dnd.jck.sh
      - FOUNDRY_PORT=30000
    ports:
      - "30000:30000"
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    environment:
      - DO_NOT_TRACK=0
      - DISABLE_CLOUD=1
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdata_config:/etc/netdata
      - netdata_lib:/var/lib/netdata
      - netdata_cache:/var/cache/netdata
      - ./netdata/conf.d:/etc/netdata/health.d
      - ./netdata/notify.d/health_alarm_notify.conf:/etc/netdata/health_alarm_notify.conf:ro
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

volumes:
  foundry_data:
  netdata_config:
  netdata_lib:
  netdata_cache: